---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrator
  namespace: pulp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: migrator-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: migrator
  namespace: pulp


---
apiVersion: batch/v1
kind: Job
metadata:
  name: pulp-migrator
  namespace: pulp
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: quay.io/rhn_support_hyagi/pulp-migrator
      restartPolicy: Never
      serviceAccount: migrator