apiVersion: batch/v1
kind: Job
metadata:
  name: pulp-migrator
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: quay.io/rhn_support_hyagi/pulp-migrator
      restartPolicy: Never
      serviceAccount: my-service-account